---
name: Renovate

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: "Dry Run"
        default: "false"
        required: false
      logLevel:
        description: "Override default log level"
        default: "debug"
        required: false
  schedule:
    - cron: "0 0 * * *" # Every day at midnight
  push:
    branches:
      - "main"
    paths:
      - .github/renovate.json
      - .github/renovate/**.json

env:
  LOG_LEVEL: debug
  RENOVATE_DRY_RUN: false
  RENOVATE_CONFIG_FILE: .github/renovate.json

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        id: generate-token
        uses: tibdex/github-app-token@v2.1.0
        with:
          app_id: "${{ secrets.BOT_APP_ID }}"
          private_key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Validate Renovate JSON
        run: jq type .github/renovate.json

      - name: Override default config with input variables
        run: |
          echo "RENOVATE_DRY_RUN=${{ github.event.inputs.dryRun || env.RENOVATE_DRY_RUN}}" >> $GITHUB_ENV
          echo "RENOVATE_DRY_RUN=${{ github.event.inputs.logLevel || env.LOG_LEVEL}}" >> $GITHUB_ENV

      - name: Renovate
        uses: renovatebot/github-action@v40.3.2
        with:
          configurationFile: "${{ env.RENOVATE_CONFIG_FILE }}"
          token: "${{ steps.generate-token.outputs.token }}"
